### ISSUE TITLE
TOD detection crashes when training has been done at 1280x1024 pixels

### ISSUE THREAD

**Issue by jordi-pages** [wg-perception/object_recognition_core#22]
This crash occurs when the objects have been trained with a Kinect at 1280x1024 pixels. Then, when running the detection as follows:

```
rosrun object_recognition_core detection -c `rospack find object_recognition_tod`/conf/detection.ros.ork --visualize
```

the following crash appears:

```
OpenCV Error: Assertion failed (func != 0) in transpose, file /home/hudson/tmp/opencv/opencv-2.4.6.1/modules/core/src/matrix.cpp, line 2023
Traceback (most recent call last):
  File "/home/jordi/branches_svn/hydro_migration/ork_ws/src/object_recognition_core/apps/detection", line 24, in <module>
    run_plasm(args, plasm)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/ecto/opts.py", line 85, in run_plasm
    sched.execute(options.niter)
ecto.CellException:            exception_type  CellException
                cell_name  pipeline1
                cell_type  ecto::py::BlackBox
            function_name  process
                     type  std::runtime_error
                     what             exception_type  CellException
                cell_name  Matcher
            function_name  process
                     type  cv::Exception
                     what  /home/hudson/tmp/opencv/opencv-2.4.6.1/modules/core/src/matrix.cpp:2023: error: (-215) func != 0 in function transpose

                     when  While triggering param change callbacks
```

This crash happens independently of the resolution at which the Kinect is operating during the detection, i.e. 640x480 or 1280x1024. That is why I guess it is a problem managing the training data stored in the database.

**Comment by kelayamatoz** [comment]
Hi jordi,

I am getting exactly the same problem as you are having here. Wondering that if you were able to figure out a solution? Many thanks! 

Best,

Tian
