### ISSUE TITLE
Seems like image ratio is fixed to 4:3, at least for detection

### ISSUE THREAD

**Issue by JimmyDaSilva** [wg-perception/object_recognition_core#38]
Everytime I have been trying to use a different ratio than 4:3 (640x480) images I have got the following error:
```
OpenCV Error: Assertion failed (0 <= _rowRange.start && _rowRange.start <= _rowRange.end && _rowRange.end <= m.rows) in Mat, file /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/matrix.cpp, line 284
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/object_recognition_core/detection", line 24, in <module>
    run_plasm(args, plasm)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/ecto/opts.py", line 85, in run_plasm
    sched.execute(options.niter)
ecto.CellException:            exception_type  CellException
[cell_name] = source1

[cell_type] = ecto::py::BlackBox

[function_name] = process_with_only_these_inputs

[type] = std::runtime_error

[what] =            exception_type  CellException
[cell_name] = Source

[cell_type] = ecto::py::BlackBox

[function_name] = process_with_only_these_inputs

[type] = std::runtime_error

[what] =            exception_type  CellException
[cell_name] = <class 'ecto_image_pipeline.base.RescaledRegisteredDepth'>

[cell_type] = RescaledRegisteredDepth

[function_name] = process_with_only_these_inputs

[type] = cv::Exception

[what] = /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/matrix.cpp:284: error: (-215) 0 <= _rowRange.start && _rowRange.start <= _rowRange.end && _rowRange.end <= m.rows in function Mat
```

It would be nice if we could use any ratio, or at least the 16:9 (i.e. 1920x1080) one so that people can use the KinectV2.
Any ratio would be great too so that people can work on cropped images.

**Comment by JimmyDaSilva** [comment]
This is only a linemod issue after all. The problem is discussed there:
https://github.com/wg-perception/linemod/issues/28
