### ISSUE TITLE
Temporary views are not supported in CouchDB

### ISSUE THREAD

**Issue by lepalom** [wg-perception/object_recognition_core#50]
Trying to use ork with a couchDB 2.0 I have found this issue:

$ rosrun object_recognition_core object_add.py -n "coke" -d "A universal beer" --commit
Traceback (most recent call last):
  File "/srv/robotica/ros/install_isolated/lib/object_recognition_core/dbscripts/object_add.py", line 35, in <module>
    db = dbtools.init_object_databases(couch)
  File "/srv/robotica/ros/install_isolated/lib/python2.7/dist-packages/object_recognition_core/db/tools.py", line 28, in init_object_databases
    models.sync_models(db)
  File "/srv/robotica/ros/install_isolated/lib/python2.7/dist-packages/object_recognition_core/db/models.py", line 187, in sync_models
    Model.sync(db)
  File "/srv/robotica/ros/install_isolated/lib/python2.7/dist-packages/object_recognition_core/db/models.py", line 166, in sync
    ''') ]
  File "/srv/robotica/ros/install_isolated/lib/python2.7/dist-packages/couchdb/client.py", line 1113, in __iter__
    return iter(self.rows)
  File "/srv/robotica/ros/install_isolated/lib/python2.7/dist-packages/couchdb/client.py", line 1132, in rows
    self._fetch()
  File "/srv/robotica/ros/install_isolated/lib/python2.7/dist-packages/couchdb/client.py", line 1119, in _fetch
    data = self.view._exec(self.options)
  File "/srv/robotica/ros/install_isolated/lib/python2.7/dist-packages/couchdb/client.py", line 1019, in _exec
    }, **_encode_view_options(options))
  File "/srv/robotica/ros/install_isolated/lib/python2.7/dist-packages/couchdb/http.py", line 452, in post_json
    status, headers, data = self.post(*a, **k)
  File "/srv/robotica/ros/install_isolated/lib/python2.7/dist-packages/couchdb/http.py", line 434, in post
    **params)
  File "/srv/robotica/ros/install_isolated/lib/python2.7/dist-packages/couchdb/http.py", line 472, in _request
    credentials=self.credentials)
  File "/srv/robotica/ros/install_isolated/lib/python2.7/dist-packages/couchdb/http.py", line 362, in request
    raise ServerError((status, error))
couchdb.http.ServerError: (403, ('forbidden', 'Temporary views are not supported in CouchDB'))

It seems that ork use a functionality (Temporally views) that are dropped in CouchDB 2.0. Do you have any idea how to solve this?

**Comment by corot** [comment]
I know nearly zero about CouchDB, but I found a shitty workaround by comparing what kinetic code does. Looks like ORK only uses temporal views on [this line](https://github.com/wg-perception/object_recognition_core/blob/master/python/object_recognition_core/db/models.py#L115), so I commented it and instead harcoded the models list:
`models = ['mesh']`

Store meshes with add_object/mesh scripts seems to work, and also retrieve for recognition. No idea about detection and training.

A sounder solution would be highly appreciated

**Comment by Doflamingooooo** [comment]
After six years, have you solved this problem? I am also facing this problem now.

**Comment by corot** [comment]
> After six years, have you solved this problem? I am also facing this problem now.

I gave up on ORK ages ago, sorry
